### ISSUE TITLE
Add FA6 thin style

### ISSUE THREAD

**Issue by ghenry** [fluttercommunity/font_awesome_flutter#100]
Hi,

Any chance of getting the FA6 thin icons in this for paid backers?

Thanks.

**Comment by michaelspiss** [comment]
Hi,
once i get my hands on fa6 I am going to add the new style. Until then, here are the steps to do it yourself:

- Run the updater tool with fa6's icons.json
- Replace the old ttf files with fa6's
- Add the thin font style to pubspec.yaml:
```yaml
    - family: FontAwesomeThin
      fonts:
        - asset: lib/fonts/fa-thin-100.ttf
          weight: 100
```
(The 100 weight and file name is a guess, please replace accordingly)
- Add following to  `font_awesome_flutter/lib/src/icon_data.dart`:
```dart
class IconDataThin extends IconData {
  const IconDataThin(int codePoint)
      : super(
          codePoint,
          fontFamily: 'FontAwesomeThin',
          fontPackage: 'font_awesome_flutter',
        );
}
```
- Run `flutter packages get`
