### ISSUE TITLE
Missing part of an icon

### ISSUE THREAD

**Issue by fareezMaple** [fluttercommunity/font_awesome_flutter#113]
Hi. I use this package in flutter.
The problem is YouTube icon is not showing correctly as it should be. Other icon i used works fine.

Look at this screenshot
![image](https://user-images.githubusercontent.com/60868965/89600489-c760f100-d894-11ea-98b3-6ab30562e4f3.png)

The code
```
linkCard(FontAwesomeIcons.youtube, 'YouTube',
                'https://www.youtube.com/', hexToColor('#F80000')),
```

Widget
```
Widget linkCard(IconData icon, String title, String url, Color color) {
  return PressableDough(
    child: Card(
      color: color,
      child: InkWell(
        splashColor: Colors.pink.withAlpha(10),
        onTap: () {
          launchURL(url);
        },
        child: ListTile(
          leading: Icon(
            icon,
            color: Colors.white,
          ),
          title: Text(
            title,
            textAlign: TextAlign.center,
            style: TextStyle(color: Colors.white),
          ),
          trailing: Icon(null),
        ),
      ),
    ),
  );
}
```

You can visit the site: https://linktree-clone-flutter.web.app/

**Comment by fareezMaple** [comment]
in pubspec.yaml

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.5.0
  dough: ^0.2.3
```
