### ISSUE TITLE
Pro icons with a CI build

### ISSUE THREAD

**Issue by ghenry** [fluttercommunity/font_awesome_flutter#121]
Hi all,

Following https://github.com/fluttercommunity/font_awesome_flutter#how-can-i-use-pro-icons what are others doing for CI builds, e.g. github workflows:

https://github.com/subosito/flutter-action

I could do https://dart.dev/tools/pub/cmd/pub-run#running-a-script-in-a-dependency or some set up first to checkout the repot and follow those steps I suppose. 

What are others doing?

Thanks.

**Comment by ghenry** [comment]
I've ended up creating a private repo on github with the pro icons and updating my pubspec like so:

```
dependency_overrides:
  font_awesome_flutter:
    git:
      url: git@github.com:ghenry/font_awesome_flutter_with_pro_icons.git
```

leaving this for others to reference (not my private repo! )

Thanks.
