### ISSUE TITLE
Missing sharp solid style in pro version?

### ISSUE THREAD

**Issue by steve3d** [fluttercommunity/font_awesome_flutter#224]
fontawesome-pro 6.2's major change is the sharp solid style icons.

Then I tried to follow the readme to create my own pro version, and I found that  the sharp solid style are completely ignored.

here is the styles: https://fontawesome.com/search?o=r&s=solid&f=sharp

as you can see, the sharp solid is just a solid variation, but in generated pubspec.yaml:
```
flutter:
  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: lib/fonts/fa-brands-400.ttf
          weight: 400
    - family: FontAwesomeRegular
      fonts:
        - asset: lib/fonts/fa-regular-400.ttf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: lib/fonts/fa-solid-900.ttf
          weight: 900
    - family: FontAwesomeLight
      fonts:
        - asset: lib/fonts/fa-light-300.ttf
          weight: 300
    - family: FontAwesomeThin
      fonts:
        - asset: lib/fonts/fa-thin-100.ttf
          weight: 100
```

there is no `fa-sharp-solid-900.ttf`, I think the simplest way and maybe annoying way is duplicate and add `sharp` prefix to all solid icons. like `FontAwesomeIcons.solidZero` and `FontAwesomeIcons.sharpSolidZero`? indeed a little strange  😅

**Comment by michaelspiss** [comment]
Hi, sharp is not supported with the newest release because the icons are limited to pro. I don't own a pro license and won't buy one just to then support a paid feature for free ([we've discussed this thoroughly with duotone support](https://github.com/fluttercommunity/font_awesome_flutter/issues/192#issuecomment-1073003668)). This means pro icons are supported solely by the community, more explicitly by people who already own/have access to a license.

Now let's get to the good part:
You may be able to get this working the following way:
add these lines to your pubspec under `fonts`:
```
    - family: FontAwesomeSharpSolid
      fonts:
        - asset: lib/fonts/fa-sharp-solid-900.ttf
          weight: 900
```
This makes sure flutter knows about the font file. 

Now take a look at the icons.json file provided in the metadata folder. Check how the sharp icons are identified - in the best case, there only is a new style named sharp-solid or something. Otherwise, this would require significant changes to the configurator tool.

I may be able to assist further once I have this piece of information.
